window.BANK_BOARD_BRANCHES = [
  {"quarter":"1","bank":"농협은행","center":"순천","branchNo":"","name":"광양시지부","address":"전남광주통합특별시 광양시 광양읍 매천로 836","phone":"","staff":"김준호","memoId":"m_12291C4A"},
  {"quarter":"1","bank":"농협은행","center":"순천","branchNo":"","name":"동광양지점","address":"전남광주통합특별시 광양시 중마중앙로 125 1층","phone":"","staff":"김준호","memoId":"m_7F7B8D17"},
  {"quarter":"1","bank":"농협은행","center":"순천","branchNo":"","name":"여수센트럴지점","address":"전남광주통합특별시 여수시 여서1로 53","phone":"","staff":"김준호","memoId":"m_5E71C5E4"},
  {"quarter":"1","bank":"농협은행","center":"순천","branchNo":"","name":"여수시청<출>","address":"전남광주통합특별시 여수시 시청로 1 NH농협은행 여수시청출장소","phone":"","staff":"김준호","memoId":"m_757B7B2B"},
  {"quarter":"1","bank":"농협은행","center":"순천","branchNo":"","name":"장흥군청<출>","address":"전남광주통합특별시 장흥군 장흥읍 장흥로 21","phone":"","staff":"장창형","memoId":"m_3CDBA70F"},
  {"quarter":"1","bank":"농협은행","center":"순천","branchNo":"","name":"보성군지부","address":"전남광주통합특별시 보성군 보성읍 현충로 91","phone":"","staff":"장창형","memoId":"m_2EE31CE3"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"장흥관산농협","address":"전남광주통합특별시 장흥군 관산읍 관산로 74","phone":"","staff":"장창형","memoId":"m_230FBAC1"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"북부농협","address":"전남광주 보성군 복내면 송재로 1829-20","phone":"총무 061-859-2837\n직원1 010-2934-7054\n직원2 010-9949-0307\n창구 061-852-5037","staff":"장창형","memoId":"m_1C3F6525"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"북부농협 겸백지점","address":"전남광주통합특별시 보성군 겸백면 충의로 2473","phone":"","staff":"장창형","memoId":"m_6FADA503"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"북부농협 문덕지점","address":"전남광주통합특별시 보성군 문덕면 장운길 60","phone":"","staff":"장창형","memoId":"m_777B73A7"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"북부농협 율어지점","address":"전남광주통합특별시 보성군 율어면 율어로 561","phone":"","staff":"장창형","memoId":"m_7E555FB6"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"장흥안양농협","address":"전남광주통합특별시 장흥군 안양면 안양로 113","phone":"","staff":"장창형","memoId":"m_30750F2A"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여수농협","address":"전남광주통합특별시 여수시 여문2로 40","phone":"","staff":"김준호","memoId":"m_20F0A448"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 엑스포지점","address":"전남광주통합특별시 여수시 덕충안길 86","phone":"","staff":"김준호","memoId":"m_52AE14E4"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 좌수영지점","address":"전남광주통합특별시 여수시 좌수영로 355","phone":"","staff":"김준호","memoId":"m_38F0369"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 충무지점","address":"전남광주통합특별시 여수시 충무1길 14","phone":"","staff":"김준호","memoId":"m_63C4C948"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 화정지점","address":"전남광주통합특별시 여수시 화정면 백야해안길 65 화정농협","phone":"","staff":"김준호","memoId":"m_68BC5F34"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여수원예농협","address":"전남광주통합특별시 여수시 무선로 219","phone":"","staff":"김준호","memoId":"m_2B270CB8"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여수원예농협 소호지점","address":"전남광주통합특별시 여수시 소호로 493","phone":"","staff":"김준호","memoId":"m_577C15C0"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 묘도<간>","address":"전남광주통합특별시 여수시 묘도1길 56","phone":"","staff":"김준호","memoId":"m_71A34B59"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 석창지점","address":"전남광주통합특별시 여수시 봉계4길 2 여천농업협동조합","phone":"","staff":"김준호","memoId":"m_416F4E3A"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 선원지점","address":"전남광주통합특별시 여수시 무선5길 26 여천농협 선원지점","phone":"","staff":"김준호","memoId":"m_4159DEB0"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 신웅천지점","address":"전남광주통합특별시 여수시 예울마루로 37-26","phone":"","staff":"김준호","memoId":"m_C47B7F2"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 안산지점","address":"전남광주통합특별시 여수시 소호로 659 부영맨션","phone":"","staff":"김준호","memoId":"m_438743B8"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 웅천동부지점","address":"전남광주통합특별시 여수시 웅천7길 15","phone":"","staff":"김준호","memoId":"m_6CBE841"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 율촌지점","address":"전남광주통합특별시 여수시 율촌면 율촌로 100-4","phone":"","staff":"김준호","memoId":"m_44C30CF4"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 화동지점","address":"전남광주통합특별시 여수시 화양면 화동로 148 화양농협","phone":"","staff":"김준호","memoId":"m_4CA9AAAD"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 화양지점","address":"전남광주통합특별시 여수시 화양면 화양로 1385","phone":"","staff":"김준호","memoId":"m_4CF50A65"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"장흥축산농협","address":"전남광주통합특별시 장흥군 장흥읍 중앙로2길 2 장흥축산농협","phone":"","staff":"장창형","memoId":"m_34ED8F36"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"장흥축산농협 관산지점","address":"전남광주통합특별시 장흥군 관산읍 칠관로 1570","phone":"","staff":"장창형","memoId":"m_461B8161"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"장흥축산농협 장흥<간>","address":"전남광주 장흥군 장흥읍 장흥대로 3244","phone":"","staff":"김준호","memoId":"m_74C9517E"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 이백지점","address":"전북특별자치도 남원시 이백면 이백로 480 이백농협","phone":"","staff":"김대한","memoId":"m_107D0A78"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"남원원예농협","address":"전북특별자치도 남원시 남문로 396-1","phone":"","staff":"김대한","memoId":"m_6596AD49"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"남원원예농협 달빛지점","address":"전북특별자치도 남원시 남문로 283 상가 1층","phone":"","staff":"김대한","memoId":"m_7391CA63"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"남원축협","address":"전북특별자치도 남원시 광한서로 88","phone":"","staff":"김대한","memoId":"m_155F1544"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"남원축협 도통중앙지점","address":"전북특별자치도 남원시 시청로 52","phone":"","staff":"김대한","memoId":"m_7CE77F83"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"운봉농협","address":"전북특별자치도 남원시 운봉읍 운봉로 679","phone":"","staff":"김대한","memoId":"m_2148CB41"},
  {"quarter":"2","bank":"농협은행","center":"순천","branchNo":"","name":"여수금융센터","address":"전남광주통합특별시 여수시 시청로 49","phone":"","staff":"김준호","memoId":"m_7A90E91"},
  {"quarter":"2","bank":"농협은행","center":"순천","branchNo":"","name":"벌교<출>","address":"전남광주통합특별시 보성군 벌교읍 채동선로 248","phone":"","staff":"장창형","memoId":"m_19C18C20"},
  {"quarter":"2","bank":"농협은행","center":"순천","branchNo":"","name":"장흥군지부","address":"전남광주통합특별시 장흥군 장흥읍 장흥로 17","phone":"","staff":"장창형","memoId":"m_7C87F1C9"},
  {"quarter":"2","bank":"농협은행","center":"순천","branchNo":"","name":"순천시청<출>","address":"전남광주통합특별시 순천시 장명로 30","phone":"","staff":"김준호","memoId":"m_2F31646"},
  {"quarter":"2","bank":"농협은행","center":"순천","branchNo":"","name":"순천금융센터","address":"전남광주통합특별시 순천시 중앙로 98","phone":"","staff":"김준호","memoId":"m_6147D534"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여수축산농협 대교지점","address":"전남광주통합특별시 여수시 신월로 692","phone":"","staff":"김준호","memoId":"m_5D84509B"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여수축산농협 서강동지점","address":"전남광주통합특별시 여수시 좌수영로 36","phone":"","staff":"김준호","memoId":"m_C5738EF"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"보성축산농협 벌교지점","address":"전남광주통합특별시 보성군 벌교읍 채동선로 266","phone":"","staff":"장창형","memoId":"m_43D77774"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여수축산농협 문수동지점","address":"전남광주통합특별시 여수시 문수로 162-1 여수축산농협","phone":"","staff":"김준호","memoId":"m_2DD0DC2D"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 우두지점","address":"전남광주통합특별시 여수시 돌산읍 강남4길 55","phone":"","staff":"김준호","memoId":"m_5FD4A90B"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 남면지점","address":"전남광주통합특별시 여수시 남면 내외진길 24 여수농협남면지점","phone":"","staff":"김준호","memoId":"m_53DA0F27"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 상암지점","address":"전남광주통합특별시 여수시 상암로 597","phone":"","staff":"김준호","memoId":"m_411F7635"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 죽림지점","address":"전남광주통합특별시 여수시 소라면 덕양로 18","phone":"","staff":"김준호","memoId":"m_45721359"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 소라지점","address":"전남광주통합특별시 여수시 소라면 덕양로 432","phone":"","staff":"김준호","memoId":"m_4153E348"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여천농협","address":"전남광주통합특별시 여수시 학동1길 19","phone":"","staff":"김준호","memoId":"m_211D5FCC"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 시전지점","address":"전남광주통합특별시 여수시 새터로 51 여천농협 시전지점","phone":"","staff":"김준호","memoId":"m_42527520"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 동부지점","address":"전남광주통합특별시 여수시 동문로 89 여수농협","phone":"","staff":"김준호","memoId":"m_55A706C4"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 여서지점","address":"전남광주통합특별시 여수시 여문문화1길 6","phone":"","staff":"김준호","memoId":"m_5F9F9E93"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 국동지점","address":"전남광주통합특별시 여수시 신월로 626","phone":"","staff":"김준호","memoId":"m_51F87871"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"보성농협 미력지점","address":"전남광주통합특별시 보성군 미력면 송재로 581","phone":"","staff":"장창형","memoId":"m_6E70AAC7"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"보성농협 만평지점","address":"전남광주통합특별시 보성군 보성읍 송재로 421","phone":"","staff":"장창형","memoId":"m_6DB55CBF"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"회천농협 회령지점","address":"전남광주통합특별시 보성군 회천면 시장길 23","phone":"","staff":"장창형","memoId":"m_61DC34C6"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"회천농협 천포지점","address":"전남광주통합특별시 보성군 회천면 공룡로 52-12 회천농협농산물집하장","phone":"","staff":"장창형","memoId":"m_5CDF0549"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"회천농협","address":"전남광주통합특별시 보성군 회천면 남부관광로 2330","phone":"","staff":"장창형","memoId":"m_2A3B2C6C"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"정남진장흥농협 서부지점","address":"전남광주통합특별시 장흥군 장흥읍 칠거리예양로 79-1","phone":"","staff":"장창형","memoId":"m_79E688FC"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"정남진장흥농협","address":"전남광주통합특별시 장흥군 장흥읍 북부로 6","phone":"","staff":"장창형","memoId":"m_62915C8D"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"정남진장흥농협 부산지점","address":"전남광주통합특별시 장흥군 부산면 부유로 15","phone":"","staff":"장창형","memoId":"m_77F96A10"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"정남진장흥농협 유치지점","address":"전남광주통합특별시 장흥군 유치면 유치로 18 유치농협","phone":"","staff":"장창형","memoId":"m_7D7AA758"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"용두농협 장동지점","address":"전남광주 장흥군 장동면 곰치로 9","phone":"","staff":"장창형","memoId":"m_74FB8AA0"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"용두농협","address":"전남광주 장흥군 장평면 장평중앙길 45","phone":"","staff":"장창형","memoId":"m_211DA81D"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"용산농협","address":"전남광주 장흥군 용산면 용안로 11","phone":"","staff":"장창형","memoId":"m_21524C7D"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 대산지점","address":"전북특별자치도 남원시 대산면 운교2길 28 농협","phone":"","staff":"김대한","memoId":"m_558FAC3"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 덕과지점","address":"전북특별자치도 남원시 덕과면 덕오로 300 덕과농협","phone":"","staff":"김대한","memoId":"m_533C644"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 도통지점","address":"전북특별자치도 남원시 용성로 220 남원농협도통점","phone":"","staff":"김대한","memoId":"m_60CDB4C"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 주천지점","address":"전북특별자치도 남원시 주천면 정령치로 81 주천농협","phone":"","staff":"김대한","memoId":"m_1199D62B"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 향교지점","address":"전북특별자치도 남원시 충정로 100","phone":"","staff":"김대한","memoId":"m_1805EBE8"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"남원농협(광주)","address":"전북특별자치도 남원시 요천로 1838","phone":"","staff":"김대한","memoId":"m_4DA8484D"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"춘향골농협","address":"전북특별자치도 남원시 금지면 금지순환길 917-31 춘향골농협","phone":"","staff":"김대한","memoId":"m_547A0E92"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"춘향골농협 대강지점","address":"전북특별자치도 남원시 대강면 섬진로 816","phone":"","staff":"김대한","memoId":"m_166FC830"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"춘향골농협 송동지점","address":"전북특별자치도 남원시 송기길 73","phone":"","staff":"김대한","memoId":"m_1E9667F5"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"춘향골농협 수지지점","address":"전북특별자치도 남원시 수지면 고주로 614 춘향골농협수지지점","phone":"","staff":"김대한","memoId":"m_1F34D4B3"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"춘향골농협 신월지점","address":"전북특별자치도 남원시 금지면 요천로 207 춘향골농협신월지점","phone":"","staff":"김대한","memoId":"m_1F96128F"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"춘향골농협 주생지점","address":"전북특별자치도 남원시 주생면 영천길 6 농협창고","phone":"","staff":"김대한","memoId":"m_22D65374"},
  {"quarter":"3","bank":"농협은행","center":"순천","branchNo":"","name":"여수시지부","address":"전남광주통합특별시 여수시 좌수영로 54 중해마루힐아너스 상가동 1층","phone":"","staff":"김준호","memoId":"m_5208ADCF"},
  {"quarter":"3","bank":"농협은행","center":"순천","branchNo":"","name":"여수2청사<출>","address":"전남광주통합특별시 여수시 여서1로 107 여서청사 민원실","phone":"","staff":"김준호","memoId":"m_75CADE9F"},
  {"quarter":"3","bank":"농협은행","center":"순천","branchNo":"","name":"보성군청<출>","address":"전남광주통합특별시 보성군 보성읍 송재로 165 보성군청","phone":"","staff":"장창형","memoId":"m_72ADFE14"},
  {"quarter":"3","bank":"농협은행","center":"순천","branchNo":"","name":"남원시지부","address":"전북특별자치도 남원시 광한북로 63 1층","phone":"","staff":"김대한","memoId":"m_53CE0040"},
  {"quarter":"3","bank":"농협은행","center":"순천","branchNo":"","name":"남원시청<출>","address":"전북특별자치도 남원시 시청로 60","phone":"","staff":"김대한","memoId":"m_7DDF2DEB"},
  {"quarter":"3","bank":"농협은행","center":"순천","branchNo":"","name":"남원지원<출>","address":"전북특별자치도 남원시 용성로 59","phone":"","staff":"김대한","memoId":"m_7758F213"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수축산농협","address":"전남광주통합특별시 여수시 소호로 638","phone":"","staff":"김준호","memoId":"m_2EC69E05"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"장흥축산농협 대덕지점","address":"전남광주 장흥군 대덕읍 대대로 982","phone":"","staff":"장창형","memoId":"m_492CF746"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"보성축산농협","address":"전남광주통합특별시 보성군 보성읍 신일길 1","phone":"","staff":"장창형","memoId":"m_32AE1D7C"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 돌산지점","address":"전남광주통합특별시 여수시 돌산읍 방답길 45 여수농협","phone":"","staff":"김준호","memoId":"m_55AD7507"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 죽포지점","address":"전남광주통합특별시 여수시 돌산읍 돌산로 2100","phone":"","staff":"김준호","memoId":"m_619E1AD4"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 양지지점","address":"전남광주통합특별시 여수시 만성로 78","phone":"","staff":"김준호","memoId":"m_5F9279BC"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 삼산지점","address":"전남광주통합특별시 여수시 삼산면 거문길 10","phone":"","staff":"김준호","memoId":"m_5CC59BF7"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수원예농협 웅천지점","address":"전남광주통합특별시 여수시 웅천로 130","phone":"","staff":"김준호","memoId":"m_5A305BBD"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수원예농협 신여서지점","address":"전남광주통합특별시 여수시 여서로 168 e-편한치과","phone":"","staff":"김준호","memoId":"m_55F3DA7A"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수축산농협 신기지점","address":"전남광주통합특별시 여수시 쌍봉로 208 주거복합동 110, 111, 112호","phone":"","staff":"김준호","memoId":"m_663C8D5B"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 죽림호수지점","address":"전남광주통합특별시 여수시 소라면 화양로 2013","phone":"","staff":"김준호","memoId":"m_711C0F37"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"전남낙농농협 순천만지점","address":"전남광주통합특별시 순천시 해룡면 신대로 55","phone":"","staff":"김준호","memoId":"m_7BD9F31D"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수원예농협 서교지점","address":"전남광주통합특별시 여수시 중앙로 2","phone":"","staff":"김준호","memoId":"m_5690A868"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"보성농협","address":"전남광주통합특별시 보성군 보성읍 현충로 92-20","phone":"","staff":"장창형","memoId":"m_1C01C7A9"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"보성농협 노동지점","address":"전남광주통합특별시 보성군 노동면 광곡길 7","phone":"","staff":"장창형","memoId":"m_689C68FB"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"보성농협 웅치지점","address":"전남광주통합특별시 보성군 웅치면 일림로 985","phone":"","staff":"장창형","memoId":"m_74BB4D67"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"득량농협 예당지점","address":"전남광주통합특별시 보성군 득량면 예당길 151","phone":"","staff":"장창형","memoId":"m_4DD93A61"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"득량농협","address":"전남광주통합특별시 보성군 득량면 역전길 48 농협창고","phone":"","staff":"장창형","memoId":"m_176A1F8A"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"벌교농협 서부지점","address":"전남광주통합특별시 보성군 조성면 예당길 210","phone":"","staff":"장창형","memoId":"m_161FCBCC"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"벌교농협 조성지점","address":"전남광주통합특별시 보성군 조성면 조성로 91","phone":"","staff":"장창형","memoId":"m_1A343691"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"벌교농협 고상지점","address":"전남광주통합특별시 보성군 벌교읍 채동선로 734-2","phone":"","staff":"장창형","memoId":"m_B152891"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"벌교농협","address":"전남광주통합특별시 보성군 벌교읍 채동선로 236","phone":"","staff":"장창형","memoId":"m_1B743020"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"천관농협","address":"전남광주통합특별시 장흥군 대덕읍 대대로 928","phone":"","staff":"장창형","memoId":"m_2441B1E0"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"천관농협 회진지점","address":"전남광주통합특별시 장흥군 회진면 회진로 447","phone":"","staff":"장창형","memoId":"m_5C83038A"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"완도농협 금당지점","address":"전남광주 완도군 금당면 울포길 10","phone":"","staff":"장창형","memoId":"m_3DD23396"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 동문지점","address":"전북특별자치도 남원시 동문로 42-1 남원농협(동문지점)","phone":"","staff":"김대한","memoId":"m_5B8B584"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 보절지점","address":"전북특별자치도 남원시 보절면 보산로 949","phone":"","staff":"김대한","memoId":"m_AED6D8F"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 사매지점","address":"전북특별자치도 남원시 사매면 덕오로 84 농협하나로마트.사매면농협","phone":"","staff":"김대한","memoId":"m_CBB4F23"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 산동지점","address":"전북특별자치도 남원시 산동면 요천로 2918 농협","phone":"","staff":"김대한","memoId":"m_CA3CBDC"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 용남지점","address":"전북특별자치도 남원시 남문로 417","phone":"","staff":"김대한","memoId":"m_FDCA7C4"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"남원원예농협 한빛지점","address":"전북특별자치도 남원시 오들로 49","phone":"","staff":"김대한","memoId":"m_67416D4"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"남원축협 하정지점","address":"전북특별자치도 남원시 광한서로 88","phone":"","staff":"김대한","memoId":"m_5EC4A5A3"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"전북지리산낙농농협","address":"전북특별자치도 남원시 의총로 28 농협","phone":"","staff":"김대한","memoId":"m_2229164"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"지리산농협","address":"전북특별자치도 남원시 인월면 인월로 100 지리산농협","phone":"","staff":"김대한","memoId":"m_7FE93F28"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"지리산농협 산내지점","address":"전북특별자치도 남원시 산내면 지리산로 1594","phone":"","staff":"김대한","memoId":"m_1D2280F7"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"지리산농협 아영지점","address":"전북특별자치도 남원시 아영면 아백로 372","phone":"","staff":"김대한","memoId":"m_1FFFC998"},
  {"quarter":"3","bank":"수협","center":"순천","branchNo":"","name":"고흥군수협 거금도지점","address":"전남광주통합특별시 고흥군 금산면 거금중앙길 76-11","phone":"","staff":"장창형","memoId":"m_2354F449"},
  {"quarter":"3","bank":"수협","center":"순천","branchNo":"","name":"고흥군수협 고흥지점","address":"전남광주통합특별시 고흥군 고흥읍 원동남계길 38","phone":"","staff":"장창형","memoId":"m_9C43430"},
  {"quarter":"3","bank":"수협","center":"순천","branchNo":"","name":"고흥군수협 과역지점","address":"전남광주통합특별시 고흥군 과역면 과역로 860-1","phone":"","staff":"장창형","memoId":"m_9893F54"},
  {"quarter":"3","bank":"수협","center":"순천","branchNo":"","name":"고흥군수협 도덕지점","address":"전남광주통합특별시 고흥군 도덕면 학동2길 9-1","phone":"","staff":"장창형","memoId":"m_CF21884"},
  {"quarter":"3","bank":"수협","center":"순천","branchNo":"","name":"고흥군수협 벌교지점","address":"전남광주통합특별시 보성군 벌교읍 홍암로 15","phone":"","staff":"장창형","memoId":"m_11A93107"},
  {"quarter":"3","bank":"수협","center":"순천","branchNo":"","name":"고흥군수협 본소","address":"전남광주 고흥군 도양읍 녹동남문길 4-5","phone":"","staff":"장창형","memoId":"m_73165C8C"},
  {"quarter":"3","bank":"수협","center":"순천","branchNo":"","name":"고흥군수협 풍화지점","address":"전남광주통합특별시 고흥군 도화면 동신길 30","phone":"","staff":"장창형","memoId":"m_1F814F6C"},
  {"quarter":"3","bank":"수협","center":"순천","branchNo":"","name":"고흥군수협 회천지점","address":"전남광주통합특별시 보성군 회천면 남부관광로 2272","phone":"","staff":"장창형","memoId":"m_20702D53"},
  {"quarter":"3","bank":"수협","center":"순천","branchNo":"","name":"나로도수협 본소","address":"전남광주 고흥군 봉래면 나로도항길 135","phone":"","staff":"장창형","memoId":"m_48A3D190"},
  {"quarter":"3","bank":"수협","center":"순천","branchNo":"","name":"장흥군수협 본소","address":"전남광주통합특별시 장흥군 회진면 가학회진로 1580","phone":"","staff":"장창형","memoId":"m_71601AF4"},
  {"quarter":"3","bank":"수협","center":"순천","branchNo":"","name":"장흥군수협 장흥읍지점","address":"전남광주통합특별시 장흥군 장흥읍 동교3길 21-1","phone":"","staff":"장창형","memoId":"m_54BD478F"},
  {"quarter":"3","bank":"수협","center":"순천","branchNo":"","name":"여수수협 순천지점","address":"전남광주통합특별시 순천시 역전광장3길 5","phone":"","staff":"김준호","memoId":"m_6FC203A0"},
  {"quarter":"3","bank":"수협","center":"순천","branchNo":"","name":"전남동부수협 광양지점","address":"전남광주통합특별시 광양시 중동로 56","phone":"","staff":"김준호","memoId":"m_8C7DF17"},
  {"quarter":"3","bank":"수협","center":"순천","branchNo":"","name":"전남동부수협 본소","address":"전남광주 여수시 율촌면 당머리길 5-1","phone":"","staff":"김준호","memoId":"m_66FAE7DD"},
  {"quarter":"3","bank":"수협","center":"순천","branchNo":"","name":"전남동부수협 왕운지점","address":"전남광주통합특별시 순천시 왕지1길 19","phone":"","staff":"김준호","memoId":"m_16A777BE"},
  {"quarter":"3","bank":"수협","center":"순천","branchNo":"","name":"하동군수협 금성지점","address":"경상남도 하동군 금성면 신도길 157","phone":"","staff":"김준호","memoId":"m_6B25D4F5"},
  {"quarter":"3","bank":"국민은행","center":"순천","branchNo":"","name":"순천종합금융센터","address":"","phone":"","staff":"장창형","memoId":"m_62E761F0"},
  {"quarter":"3","bank":"국민은행","center":"순천","branchNo":"","name":"여수종합금융센터","address":"","phone":"","staff":"김준호","memoId":"m_267C6393"},
  {"quarter":"3","bank":"국민은행","center":"순천","branchNo":"","name":"동광양","address":"","phone":"","staff":"김준호","memoId":"m_4D95366"},
  {"quarter":"3","bank":"국민은행","center":"순천","branchNo":"","name":"남원","address":"","phone":"","staff":"김대한","memoId":"m_70A16726"},
  {"quarter":"3","bank":"국민은행","center":"순천","branchNo":"","name":"신대","address":"","phone":"","staff":"김준호","memoId":"m_70A3AC8E"},
  {"quarter":"3","bank":"국민은행","center":"순천","branchNo":"","name":"여서동","address":"","phone":"","staff":"김준호","memoId":"m_528B9EC"},
  {"quarter":"3","bank":"기업은행","center":"순천","branchNo":"","name":"순천","address":"","phone":"","staff":"김준호","memoId":"m_668A83F5"},
  {"quarter":"3","bank":"기업은행","center":"순천","branchNo":"","name":"여수","address":"","phone":"","staff":"김준호","memoId":"m_668AF741"},
  {"quarter":"3","bank":"기업은행","center":"순천","branchNo":"","name":"남원","address":"","phone":"","staff":"김대한","memoId":"m_66883E35"},
  {"quarter":"","bank":"메리츠","center":"순천","branchNo":"","name":"순천센터","address":"","phone":"","staff":"김대한","memoId":"m_2C510E6A"},
  {"quarter":"","bank":"신한은행","center":"순천","branchNo":"","name":"순천법원","address":"","phone":"","staff":"순천","memoId":"m_383A14E1"},
  {"quarter":"","bank":"신한은행","center":"순천","branchNo":"","name":"여수종합금융센터","address":"","phone":"","staff":"순천","memoId":"m_463CBA9E"}
];
