window.BANK_BOARD_BRANCHES = [
  {"quarter":"1","bank":"농협은행","center":"순천","branchNo":"","name":"광양시지부","address":"전남광주통합특별시 광양시 광양읍 매천로 836","phone":"","staff":"김준호","memoId":"m_12291C4A"},
  {"quarter":"1","bank":"농협은행","center":"순천","branchNo":"","name":"동광양지점","address":"전남광주통합특별시 광양시 중마중앙로 125 1층","phone":"","staff":"김준호","memoId":"m_7F7B8D17"},
  {"quarter":"1","bank":"농협은행","center":"순천","branchNo":"","name":"여수센트럴지점","address":"전남광주통합특별시 여수시 여서1로 53","phone":"","staff":"김준호","memoId":"m_5E71C5E4"},
  {"quarter":"1","bank":"농협은행","center":"순천","branchNo":"","name":"여수시청<출>","address":"전남광주통합특별시 여수시 시청로 1 NH농협은행 여수시청출장소","phone":"","staff":"김준호","memoId":"m_757B7B2B"},
  {"quarter":"1","bank":"농협은행","center":"순천","branchNo":"","name":"장흥군청<출>","address":"전남광주통합특별시 장흥군 장흥읍 장흥로 21","phone":"","staff":"장창형","memoId":"m_3CDBA70F"},
  {"quarter":"1","bank":"농협은행","center":"순천","branchNo":"","name":"보성군지부","address":"전남광주통합특별시 보성군 보성읍 현충로 91","phone":"","staff":"장창형","memoId":"m_2EE31CE3"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"장흥관산농협","address":"전남광주통합특별시 장흥군 관산읍 관산로 74","phone":"","staff":"장창형","memoId":"m_230FBAC1"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"북부농협","address":"전남광주 보성군 복내면 송재로 1829-20","phone":"총무 061-859-2837\n직원1 010-2934-7054\n직원2 010-9949-0307\n창구 061-852-5037","staff":"장창형","memoId":"m_1C3F6525"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"북부농협 겸백지점","address":"전남광주통합특별시 보성군 겸백면 충의로 2473","phone":"","staff":"장창형","memoId":"m_6FADA503"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"북부농협 문덕지점","address":"전남광주통합특별시 보성군 문덕면 장운길 60","phone":"","staff":"장창형","memoId":"m_777B73A7"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"북부농협 율어지점","address":"전남광주통합특별시 보성군 율어면 율어로 561","phone":"","staff":"장창형","memoId":"m_7E555FB6"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"장흥안양농협","address":"전남광주통합특별시 장흥군 안양면 안양로 113","phone":"","staff":"장창형","memoId":"m_30750F2A"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여수농협","address":"전남광주통합특별시 여수시 여문2로 40","phone":"","staff":"김준호","memoId":"m_20F0A448"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 엑스포지점","address":"전남광주통합특별시 여수시 덕충안길 86","phone":"","staff":"김준호","memoId":"m_52AE14E4"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 좌수영지점","address":"전남광주통합특별시 여수시 좌수영로 355","phone":"","staff":"김준호","memoId":"m_38F0369"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 충무지점","address":"전남광주통합특별시 여수시 충무1길 14","phone":"","staff":"김준호","memoId":"m_63C4C948"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 화정지점","address":"전남광주통합특별시 여수시 화정면 백야해안길 65 화정농협","phone":"","staff":"김준호","memoId":"m_68BC5F34"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여수원예농협","address":"전남광주통합특별시 여수시 무선로 219","phone":"","staff":"김준호","memoId":"m_2B270CB8"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여수원예농협 소호지점","address":"전남광주통합특별시 여수시 소호로 493","phone":"","staff":"김준호","memoId":"m_577C15C0"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 묘도<간>","address":"전남광주통합특별시 여수시 묘도1길 56","phone":"","staff":"김준호","memoId":"m_71A34B59"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 석창지점","address":"전남광주통합특별시 여수시 봉계4길 2 여천농업협동조합","phone":"","staff":"김준호","memoId":"m_416F4E3A"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 선원지점","address":"전남광주통합특별시 여수시 무선5길 26 여천농협 선원지점","phone":"","staff":"김준호","memoId":"m_4159DEB0"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 신웅천지점","address":"전남광주통합특별시 여수시 예울마루로 37-26","phone":"","staff":"김준호","memoId":"m_C47B7F2"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 안산지점","address":"전남광주통합특별시 여수시 소호로 659 부영맨션","phone":"","staff":"김준호","memoId":"m_438743B8"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 웅천동부지점","address":"전남광주통합특별시 여수시 웅천7길 15","phone":"","staff":"김준호","memoId":"m_6CBE841"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 율촌지점","address":"전남광주통합특별시 여수시 율촌면 율촌로 100-4","phone":"","staff":"김준호","memoId":"m_44C30CF4"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 화동지점","address":"전남광주통합특별시 여수시 화양면 화동로 148 화양농협","phone":"","staff":"김준호","memoId":"m_4CA9AAAD"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 화양지점","address":"전남광주통합특별시 여수시 화양면 화양로 1385","phone":"","staff":"김준호","memoId":"m_4CF50A65"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"장흥축산농협","address":"전남광주통합특별시 장흥군 장흥읍 중앙로2길 2 장흥축산농협","phone":"","staff":"장창형","memoId":"m_34ED8F36"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"장흥축산농협 관산지점","address":"전남광주통합특별시 장흥군 관산읍 칠관로 1570","phone":"","staff":"장창형","memoId":"m_461B8161"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"장흥축산농협 장흥<간>","address":"전남광주 장흥군 장흥읍 장흥대로 3244","phone":"","staff":"김준호","memoId":"m_74C9517E"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 이백지점","address":"전북특별자치도 남원시 이백면 이백로 480 이백농협","phone":"","staff":"김대한","memoId":"m_107D0A78"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"남원원예농협","address":"전북특별자치도 남원시 남문로 396-1","phone":"","staff":"김대한","memoId":"m_6596AD49"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"남원원예농협 달빛지점","address":"전북특별자치도 남원시 남문로 283 상가 1층","phone":"","staff":"김대한","memoId":"m_7391CA63"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"남원축협","address":"전북특별자치도 남원시 광한서로 88","phone":"","staff":"김대한","memoId":"m_155F1544"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"남원축협 도통중앙지점","address":"전북특별자치도 남원시 시청로 52","phone":"","staff":"김대한","memoId":"m_7CE77F83"},
  {"quarter":"1","bank":"농축협","center":"순천","branchNo":"","name":"운봉농협","address":"전북특별자치도 남원시 운봉읍 운봉로 679","phone":"","staff":"김대한","memoId":"m_2148CB41"},
  {"quarter":"2","bank":"농협은행","center":"순천","branchNo":"","name":"여수금융센터","address":"전남광주통합특별시 여수시 시청로 49","phone":"","staff":"김준호","memoId":"m_7A90E91"},
  {"quarter":"2","bank":"농협은행","center":"순천","branchNo":"","name":"벌교<출>","address":"전남광주통합특별시 보성군 벌교읍 채동선로 248","phone":"","staff":"장창형","memoId":"m_19C18C20"},
  {"quarter":"2","bank":"농협은행","center":"순천","branchNo":"","name":"장흥군지부","address":"전남광주통합특별시 장흥군 장흥읍 장흥로 17","phone":"","staff":"장창형","memoId":"m_7C87F1C9"},
  {"quarter":"2","bank":"농협은행","center":"순천","branchNo":"","name":"순천시청<출>","address":"전남광주통합특별시 순천시 장명로 30","phone":"","staff":"김준호","memoId":"m_2F31646"},
  {"quarter":"2","bank":"농협은행","center":"순천","branchNo":"","name":"순천금융센터","address":"전남광주통합특별시 순천시 중앙로 98","phone":"","staff":"김준호","memoId":"m_6147D534"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여수축산농협 대교지점","address":"전남광주통합특별시 여수시 신월로 692","phone":"","staff":"김준호","memoId":"m_5D84509B"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여수축산농협 서강동지점","address":"전남광주통합특별시 여수시 좌수영로 36","phone":"","staff":"김준호","memoId":"m_C5738EF"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"보성축산농협 벌교지점","address":"전남광주통합특별시 보성군 벌교읍 채동선로 266","phone":"","staff":"장창형","memoId":"m_43D77774"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여수축산농협 문수동지점","address":"전남광주통합특별시 여수시 문수로 162-1 여수축산농협","phone":"","staff":"김준호","memoId":"m_2DD0DC2D"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 우두지점","address":"전남광주통합특별시 여수시 돌산읍 강남4길 55","phone":"","staff":"김준호","memoId":"m_5FD4A90B"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 남면지점","address":"전남광주통합특별시 여수시 남면 내외진길 24 여수농협남면지점","phone":"","staff":"김준호","memoId":"m_53DA0F27"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 상암지점","address":"전남광주통합특별시 여수시 상암로 597","phone":"","staff":"김준호","memoId":"m_411F7635"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 죽림지점","address":"전남광주통합특별시 여수시 소라면 덕양로 18","phone":"","staff":"김준호","memoId":"m_45721359"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 소라지점","address":"전남광주통합특별시 여수시 소라면 덕양로 432","phone":"","staff":"김준호","memoId":"m_4153E348"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여천농협","address":"전남광주통합특별시 여수시 학동1길 19","phone":"","staff":"김준호","memoId":"m_211D5FCC"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 시전지점","address":"전남광주통합특별시 여수시 새터로 51 여천농협 시전지점","phone":"","staff":"김준호","memoId":"m_42527520"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 동부지점","address":"전남광주통합특별시 여수시 동문로 89 여수농협","phone":"","staff":"김준호","memoId":"m_55A706C4"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 여서지점","address":"전남광주통합특별시 여수시 여문문화1길 6","phone":"","staff":"김준호","memoId":"m_5F9F9E93"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 국동지점","address":"전남광주통합특별시 여수시 신월로 626","phone":"","staff":"김준호","memoId":"m_51F87871"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"보성농협 미력지점","address":"전남광주통합특별시 보성군 미력면 송재로 581","phone":"","staff":"장창형","memoId":"m_6E70AAC7"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"보성농협 만평지점","address":"전남광주통합특별시 보성군 보성읍 송재로 421","phone":"","staff":"장창형","memoId":"m_6DB55CBF"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"회천농협 회령지점","address":"전남광주통합특별시 보성군 회천면 시장길 23","phone":"","staff":"장창형","memoId":"m_61DC34C6"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"회천농협 천포지점","address":"전남광주통합특별시 보성군 회천면 공룡로 52-12 회천농협농산물집하장","phone":"","staff":"장창형","memoId":"m_5CDF0549"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"회천농협","address":"전남광주통합특별시 보성군 회천면 남부관광로 2330","phone":"","staff":"장창형","memoId":"m_2A3B2C6C"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"정남진장흥농협 서부지점","address":"전남광주통합특별시 장흥군 장흥읍 칠거리예양로 79-1","phone":"","staff":"장창형","memoId":"m_79E688FC"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"정남진장흥농협","address":"전남광주통합특별시 장흥군 장흥읍 북부로 6","phone":"","staff":"장창형","memoId":"m_62915C8D"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"정남진장흥농협 부산지점","address":"전남광주통합특별시 장흥군 부산면 부유로 15","phone":"","staff":"장창형","memoId":"m_77F96A10"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"정남진장흥농협 유치지점","address":"전남광주통합특별시 장흥군 유치면 유치로 18 유치농협","phone":"","staff":"장창형","memoId":"m_7D7AA758"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"용두농협 장동지점","address":"전남광주 장흥군 장동면 곰치로 9","phone":"","staff":"장창형","memoId":"m_74FB8AA0"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"용두농협","address":"전남광주 장흥군 장평면 장평중앙길 45","phone":"","staff":"장창형","memoId":"m_211DA81D"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"용산농협","address":"전남광주 장흥군 용산면 용안로 11","phone":"","staff":"장창형","memoId":"m_21524C7D"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 대산지점","address":"전북특별자치도 남원시 대산면 운교2길 28 농협","phone":"","staff":"김대한","memoId":"m_558FAC3"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 덕과지점","address":"전북특별자치도 남원시 덕과면 덕오로 300 덕과농협","phone":"","staff":"김대한","memoId":"m_533C644"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 도통지점","address":"전북특별자치도 남원시 용성로 220 남원농협도통점","phone":"","staff":"김대한","memoId":"m_60CDB4C"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 주천지점","address":"전북특별자치도 남원시 주천면 정령치로 81 주천농협","phone":"","staff":"김대한","memoId":"m_1199D62B"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 향교지점","address":"전북특별자치도 남원시 충정로 100","phone":"","staff":"김대한","memoId":"m_1805EBE8"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"남원농협(광주)","address":"전북특별자치도 남원시 요천로 1838","phone":"","staff":"김대한","memoId":"m_4DA8484D"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"춘향골농협","address":"전북특별자치도 남원시 금지면 금지순환길 917-31 춘향골농협","phone":"","staff":"김대한","memoId":"m_547A0E92"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"춘향골농협 대강지점","address":"전북특별자치도 남원시 대강면 섬진로 816","phone":"","staff":"김대한","memoId":"m_166FC830"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"춘향골농협 송동지점","address":"전북특별자치도 남원시 송기길 73","phone":"","staff":"김대한","memoId":"m_1E9667F5"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"춘향골농협 수지지점","address":"전북특별자치도 남원시 수지면 고주로 614 춘향골농협수지지점","phone":"","staff":"김대한","memoId":"m_1F34D4B3"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"춘향골농협 신월지점","address":"전북특별자치도 남원시 금지면 요천로 207 춘향골농협신월지점","phone":"","staff":"김대한","memoId":"m_1F96128F"},
  {"quarter":"2","bank":"농축협","center":"순천","branchNo":"","name":"춘향골농협 주생지점","address":"전북특별자치도 남원시 주생면 영천길 6 농협창고","phone":"","staff":"김대한","memoId":"m_22D65374"},
  {"quarter":"3","bank":"농협은행","center":"순천","branchNo":"","name":"여수시지부","address":"전남광주통합특별시 여수시 좌수영로 54 중해마루힐아너스 상가동 1층","phone":"","staff":"김준호","memoId":"m_5208ADCF"},
  {"quarter":"3","bank":"농협은행","center":"순천","branchNo":"","name":"여수2청사<출>","address":"전남광주통합특별시 여수시 여서1로 107 여서청사 민원실","phone":"","staff":"김준호","memoId":"m_75CADE9F"},
  {"quarter":"3","bank":"농협은행","center":"순천","branchNo":"","name":"보성군청<출>","address":"전남광주통합특별시 보성군 보성읍 송재로 165 보성군청","phone":"","staff":"장창형","memoId":"m_72ADFE14"},
  {"quarter":"3","bank":"농협은행","center":"순천","branchNo":"","name":"남원시지부","address":"전북특별자치도 남원시 광한북로 63 1층","phone":"","staff":"김대한","memoId":"m_53CE0040"},
  {"quarter":"3","bank":"농협은행","center":"순천","branchNo":"","name":"남원시청<출>","address":"전북특별자치도 남원시 시청로 60","phone":"","staff":"김대한","memoId":"m_7DDF2DEB"},
  {"quarter":"3","bank":"농협은행","center":"순천","branchNo":"","name":"남원지원<출>","address":"전북특별자치도 남원시 용성로 59","phone":"","staff":"김대한","memoId":"m_7758F213"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수축산농협","address":"전남광주통합특별시 여수시 소호로 638","phone":"","staff":"김준호","memoId":"m_2EC69E05"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"장흥축산농협 대덕지점","address":"전남광주 장흥군 대덕읍 대대로 982","phone":"","staff":"장창형","memoId":"m_492CF746"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"보성축산농협","address":"전남광주통합특별시 보성군 보성읍 신일길 1","phone":"","staff":"장창형","memoId":"m_32AE1D7C"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 돌산지점","address":"전남광주통합특별시 여수시 돌산읍 방답길 45 여수농협","phone":"","staff":"김준호","memoId":"m_55AD7507"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 죽포지점","address":"전남광주통합특별시 여수시 돌산읍 돌산로 2100","phone":"","staff":"김준호","memoId":"m_619E1AD4"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 양지지점","address":"전남광주통합특별시 여수시 만성로 78","phone":"","staff":"김준호","memoId":"m_5F9279BC"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수농협 삼산지점","address":"전남광주통합특별시 여수시 삼산면 거문길 10","phone":"","staff":"김준호","memoId":"m_5CC59BF7"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수원예농협 웅천지점","address":"전남광주통합특별시 여수시 웅천로 130","phone":"","staff":"김준호","memoId":"m_5A305BBD"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수원예농협 신여서지점","address":"전남광주통합특별시 여수시 여서로 168 e-편한치과","phone":"","staff":"김준호","memoId":"m_55F3DA7A"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수축산농협 신기지점","address":"전남광주통합특별시 여수시 쌍봉로 208 주거복합동 110, 111, 112호","phone":"","staff":"김준호","memoId":"m_663C8D5B"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여천농협 죽림호수지점","address":"전남광주통합특별시 여수시 소라면 화양로 2013","phone":"","staff":"김준호","memoId":"m_711C0F37"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"전남낙농농협 순천만지점","address":"전남광주통합특별시 순천시 해룡면 신대로 55","phone":"","staff":"김준호","memoId":"m_7BD9F31D"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"여수원예농협 서교지점","address":"전남광주통합특별시 여수시 중앙로 2","phone":"","staff":"김준호","memoId":"m_5690A868"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"보성농협","address":"전남광주통합특별시 보성군 보성읍 현충로 92-20","phone":"","staff":"장창형","memoId":"m_1C01C7A9"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"보성농협 노동지점","address":"전남광주통합특별시 보성군 노동면 광곡길 7","phone":"","staff":"장창형","memoId":"m_689C68FB"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"보성농협 웅치지점","address":"전남광주통합특별시 보성군 웅치면 일림로 985","phone":"","staff":"장창형","memoId":"m_74BB4D67"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"득량농협 예당지점","address":"전남광주통합특별시 보성군 득량면 예당길 151","phone":"","staff":"장창형","memoId":"m_4DD93A61"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"득량농협","address":"전남광주통합특별시 보성군 득량면 역전길 48 농협창고","phone":"","staff":"장창형","memoId":"m_176A1F8A"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"벌교농협 서부지점","address":"전남광주통합특별시 보성군 조성면 예당길 210","phone":"","staff":"장창형","memoId":"m_161FCBCC"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"벌교농협 조성지점","address":"전남광주통합특별시 보성군 조성면 조성로 91","phone":"","staff":"장창형","memoId":"m_1A343691"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"벌교농협 고상지점","address":"전남광주통합특별시 보성군 벌교읍 채동선로 734-2","phone":"","staff":"장창형","memoId":"m_B152891"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"벌교농협","address":"전남광주통합특별시 보성군 벌교읍 채동선로 236","phone":"","staff":"장창형","memoId":"m_1B743020"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"천관농협","address":"전남광주통합특별시 장흥군 대덕읍 대대로 928","phone":"","staff":"장창형","memoId":"m_2441B1E0"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"천관농협 회진지점","address":"전남광주통합특별시 장흥군 회진면 회진로 447","phone":"","staff":"장창형","memoId":"m_5C83038A"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"완도농협 금당지점","address":"전남광주 완도군 금당면 울포길 10","phone":"","staff":"장창형","memoId":"m_3DD23396"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 동문지점","address":"전북특별자치도 남원시 동문로 42-1 남원농협(동문지점)","phone":"","staff":"김대한","memoId":"m_5B8B584"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 보절지점","address":"전북특별자치도 남원시 보절면 보산로 949","phone":"","staff":"김대한","memoId":"m_AED6D8F"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 사매지점","address":"전북특별자치도 남원시 사매면 덕오로 84 농협하나로마트.사매면농협","phone":"","staff":"김대한","memoId":"m_CBB4F23"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 산동지점","address":"전북특별자치도 남원시 산동면 요천로 2918 농협","phone":"","staff":"김대한","memoId":"m_CA3CBDC"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"남원농협 용남지점","address":"전북특별자치도 남원시 남문로 417","phone":"","staff":"김대한","memoId":"m_FDCA7C4"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"남원원예농협 한빛지점","address":"전북특별자치도 남원시 오들로 49","phone":"","staff":"김대한","memoId":"m_67416D4"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"남원축협 하정지점","address":"전북특별자치도 남원시 광한서로 88","phone":"","staff":"김대한","memoId":"m_5EC4A5A3"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"전북지리산낙농농협","address":"전북특별자치도 남원시 의총로 28 농협","phone":"","staff":"김대한","memoId":"m_2229164"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"지리산농협","address":"전북특별자치도 남원시 인월면 인월로 100 지리산농협","phone":"","staff":"김대한","memoId":"m_7FE93F28"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"지리산농협 산내지점","address":"전북특별자치도 남원시 산내면 지리산로 1594","phone":"","staff":"김대한","memoId":"m_1D2280F7"},
  {"quarter":"3","bank":"농축협","center":"순천","branchNo":"","name":"지리산농협 아영지점","address":"전북특별자치도 남원시 아영면 아백로 372","phone":"","staff":"김대한","memoId":"m_1FFFC998"},
  {"quarter":"4","bank":"수협","center":"순천","branchNo":"","name":"고흥군수협 거금도지점","address":"전남광주통합특별시 고흥군 금산면 거금중앙길 76-11","phone":"","staff":"장창형","memoId":"m_2354F449"},
  {"quarter":"4","bank":"수협","center":"순천","branchNo":"","name":"고흥군수협 고흥지점","address":"전남광주통합특별시 고흥군 고흥읍 원동남계길 38","phone":"","staff":"장창형","memoId":"m_9C43430"},
  {"quarter":"4","bank":"수협","center":"순천","branchNo":"","name":"고흥군수협 과역지점","address":"전남광주통합특별시 고흥군 과역면 과역로 860-1","phone":"","staff":"장창형","memoId":"m_9893F54"},
  {"quarter":"4","bank":"수협","center":"순천","branchNo":"","name":"고흥군수협 도덕지점","address":"전남광주통합특별시 고흥군 도덕면 학동2길 9-1","phone":"","staff":"장창형","memoId":"m_CF21884"},
  {"quarter":"4","bank":"수협","center":"순천","branchNo":"","name":"고흥군수협 벌교지점","address":"전남광주통합특별시 보성군 벌교읍 홍암로 15","phone":"","staff":"장창형","memoId":"m_11A93107"},
  {"quarter":"4","bank":"수협","center":"순천","branchNo":"","name":"고흥군수협 본소","address":"전남광주 고흥군 도양읍 녹동남문길 4-5","phone":"","staff":"장창형","memoId":"m_73165C8C"},
  {"quarter":"4","bank":"수협","center":"순천","branchNo":"","name":"고흥군수협 풍화지점","address":"전남광주통합특별시 고흥군 도화면 동신길 30","phone":"","staff":"장창형","memoId":"m_1F814F6C"},
  {"quarter":"4","bank":"수협","center":"순천","branchNo":"","name":"고흥군수협 회천지점","address":"전남광주통합특별시 보성군 회천면 남부관광로 2272","phone":"","staff":"장창형","memoId":"m_20702D53"},
  {"quarter":"4","bank":"수협","center":"순천","branchNo":"","name":"나로도수협 본소","address":"전남광주 고흥군 봉래면 나로도항길 135","phone":"","staff":"장창형","memoId":"m_48A3D190"},
  {"quarter":"4","bank":"수협","center":"순천","branchNo":"","name":"장흥군수협 본소","address":"전남광주통합특별시 장흥군 회진면 가학회진로 1580","phone":"","staff":"장창형","memoId":"m_71601AF4"},
  {"quarter":"4","bank":"수협","center":"순천","branchNo":"","name":"장흥군수협 장흥읍지점","address":"전남광주통합특별시 장흥군 장흥읍 동교3길 21-1","phone":"","staff":"장창형","memoId":"m_54BD478F"},
  {"quarter":"4","bank":"수협","center":"순천","branchNo":"","name":"여수수협 순천지점","address":"전남광주통합특별시 순천시 역전광장3길 5","phone":"","staff":"김준호","memoId":"m_6FC203A0"},
  {"quarter":"4","bank":"수협","center":"순천","branchNo":"","name":"전남동부수협 광양지점","address":"전남광주통합특별시 광양시 중동로 56","phone":"","staff":"김준호","memoId":"m_8C7DF17"},
  {"quarter":"4","bank":"수협","center":"순천","branchNo":"","name":"전남동부수협 본소","address":"전남광주 여수시 율촌면 당머리길 5-1","phone":"","staff":"김준호","memoId":"m_66FAE7DD"},
  {"quarter":"4","bank":"수협","center":"순천","branchNo":"","name":"전남동부수협 왕운지점","address":"전남광주통합특별시 순천시 왕지1길 19","phone":"","staff":"김준호","memoId":"m_16A777BE"},
  {"quarter":"4","bank":"수협","center":"순천","branchNo":"","name":"하동군수협 금성지점","address":"경상남도 하동군 금성면 신도길 157","phone":"","staff":"김준호","memoId":"m_6B25D4F5"},
  {"quarter":"4","bank":"국민은행","center":"순천","branchNo":"","name":"순천종합금융센터","address":"전남광주 순천시 연향번영길 149 1층","phone":"","staff":"장창형","memoId":"m_62E761F0"},
  {"quarter":"4","bank":"국민은행","center":"순천","branchNo":"","name":"여수종합금융센터","address":"전남광주 여수시 시청로 24 국민은행","phone":"","staff":"김준호","memoId":"m_267C6393"},
  {"quarter":"4","bank":"국민은행","center":"순천","branchNo":"","name":"동광양","address":"전남광주 광양시 광장로 109","phone":"","staff":"김준호","memoId":"m_4D95366"},
  {"quarter":"4","bank":"국민은행","center":"순천","branchNo":"","name":"남원","address":"전북특별자치도 남원시 광한서로 64","phone":"","staff":"김대한","memoId":"m_70A16726"},
  {"quarter":"4","bank":"국민은행","center":"순천","branchNo":"","name":"신대","address":"전남광주통합특별시 순천시 해룡면 향매로 59","phone":"","staff":"김준호","memoId":"m_70A3AC8E"},
  {"quarter":"4","bank":"국민은행","center":"순천","branchNo":"","name":"여서동","address":"전남광주 여수시 문수로 106 (문수동) 1층","phone":"","staff":"김준호","memoId":"m_528B9EC"},
  {"quarter":"3","bank":"기업은행","center":"순천","branchNo":"","name":"순천","address":"전남광주통합특별시 순천시 장선배기길 6-4 2층","phone":"","staff":"김준호","memoId":"m_668A83F5"},
  {"quarter":"3","bank":"기업은행","center":"순천","branchNo":"","name":"여수","address":"전남광주통합특별시 여수시 통제영5길 6","phone":"","staff":"김준호","memoId":"m_668AF741"},
  {"quarter":"3","bank":"기업은행","center":"순천","branchNo":"","name":"남원","address":"전북특별자치도 남원시 남문로 462","phone":"","staff":"김대한","memoId":"m_66883E35"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S041840","name":"에이비에이금융서비스 유한회사(프로)","address":"전남 고흥군 고흥읍 백련장전길21,","phone":"전화 010-6889-6621","staff":"김대한","memoId":"m_7AE2D166"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"S013501","name":"전남동부권본부(광양)","address":"전남 고흥군 고흥읍 봉동주공길38-1,","phone":"전화 010-5253-0075","staff":"순천","memoId":"m_934221F"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S035014","name":"한솔금융서비스 주식회사","address":"전남 고흥군 고흥읍 봉황길9,","phone":"전화 010-6646-4387","staff":"순천","memoId":"m_6DBB2E85"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S030528","name":"(주)드림라이프(고흥)","address":"전남 고흥군 고흥읍 터미널길3,","phone":"전화 061-832-8853","staff":"김대한","memoId":"m_3FEB2594"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S001002","name":"유퍼스트보험마케팅(주)(광양지사)","address":"전남 광양시 공영로 65 (중동)","phone":"전화 061-795-0021","staff":"김대한","memoId":"m_381D5707"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S005373","name":"주식회사 더금융서비스(동행지점)","address":"전남 광양시 광양읍 희양현로11-1,","phone":"전화 061-762-6501","staff":"김대한","memoId":"m_485A38C7"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S021608","name":"인카금융서비스(주)(순천행복)","address":"전남 광양시 광장로120,","phone":"전화 010-4210-7252","staff":"김대한","memoId":"m_44B41C64"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S045404","name":"인카금융서비스(주)(이룸)","address":"전남 광양시 구마길61,","phone":"전화 010-4210-7252","staff":"김대한","memoId":"m_7C06585C"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S040967","name":"(주)영진에셋(광양)","address":"전남 광양시 길호2길12,","phone":"전화 061-913-1951","staff":"김대한","memoId":"m_535D92FB"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S007240","name":"인카금융서비스(주)(순천)","address":"전남 광양시 등논1길15-2,","phone":"전화 061-791-2234","staff":"김대한","memoId":"m_7BF22528"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S031501","name":"케이지에이에셋(주)(순천)","address":"전남 광양시 발섬2길7-1,","phone":"전화 010-2652-5973","staff":"김대한","memoId":"m_6FFB14E0"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S040951","name":"신한금융플러스 주식회사(광양지점)","address":"전남 광양시 발섬6길20,","phone":"전화 010-3780-9204","staff":"김대한","memoId":"m_4529D218"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S023659","name":"신한금융플러스 주식회사(광양지점)","address":"전남 광양시 중동로49,","phone":"전화 061-793-8446","staff":"김대한","memoId":"m_4529D218"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S003344","name":"지에이코리아주식회사(광양)","address":"전남 광양시 중동로79,","phone":"전화 061-791-1482","staff":"김대한","memoId":"m_35710E94"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S020732","name":"메가(주)(인슈전남본부)","address":"전남 광양시 중마로339,","phone":"전화 061-818-8880","staff":"김대한","memoId":"m_1D8B1304"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S015629","name":"(주)메타리치(광양)","address":"전남 광양시 중마용소3길51,","phone":"전화 061-911-9171","staff":"김대한","memoId":"m_14C30519"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S025071","name":"(주)아이에프씨그룹(광양지점)","address":"전남 광양시 중마중앙로13,","phone":"전화 061-795-9960","staff":"김대한","memoId":"m_2DEC343"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S010331","name":"인카금융서비스(주) 본사","address":"전남 광양시 진등1길3-12,","phone":"전화 010-3622-7469","staff":"김대한","memoId":"m_7A1A5A2"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S021574","name":"아이에프에이(주)(그린)","address":"전남 광양시 폭포사랑길96,","phone":"전화 061-792-5342","staff":"김대한","memoId":"m_5F6919BF"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D003301","name":"전남동부권본부","address":"전남 광양시 항만13로23-7,","phone":"전화 061-241-9300","staff":"김대한","memoId":"m_160D5EB2"},
  {"quarter":"TA_교육장","bank":"메리츠","center":"순천","branchNo":"D003723","name":"순천센터","address":"전남 광양시 항만13로23-7,","phone":"전화 061-798-4702","staff":"김대한","memoId":"m_2C510E6A"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S007046","name":"(주)에이플러스에셋어드바이저 본사","address":"전남 구례군 구례읍 구례로504,","phone":"전화 010-8258-7382","staff":"김대한","memoId":"m_300743B6"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S010539","name":"에이티에셋 주식회사(광주순천)","address":"전남 순천시 구암2길 3 (연향동)","phone":"전화 061-723-4466","staff":"김대한","memoId":"m_2A04C7DF"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S040542","name":"(주)현대홈쇼핑 본사","address":"전남 순천시 기적의도서관길22,","phone":"전화 061-726-7779","staff":"김대한","memoId":"m_2D9E6D06"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S031729","name":"케이지에이에셋(주)(천야지사유플러스)","address":"전남 순천시 기적의도서관길30,","phone":"전화 061-727-9889","staff":"김대한","memoId":"m_D3F561C"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S017029","name":"(주)글로벌금융판매(오에스케이이음)","address":"전남 순천시 남신월길15-1,","phone":"전화 061-721-1162","staff":"김대한","memoId":"m_338148A3"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S041955","name":"(주)글로벌금융판매(다모아순천)","address":"전남 순천시 대석1길16,","phone":"전화 061-746-8816","staff":"김대한","memoId":"m_62E48C63"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S017713","name":"아이에프에이(주)(에인스에이스지점)","address":"전남 순천시 대석길10,","phone":"전화 010-6404-0724","staff":"김대한","memoId":"m_17F80144"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S018444","name":"굿리치주식회사(다원)","address":"전남 순천시 백강로367,","phone":"전화 061-913-0167","staff":"김대한","memoId":"m_1EA40DD8"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S040298","name":"굿리치주식회사(호남본부)","address":"전남 순천시 백강로367,","phone":"전화 010-2349-5114","staff":"김대한","memoId":"m_4E3DE745"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S024479","name":"(주)인스밸리(경주지점)","address":"전남 순천시 백연길86,","phone":"전화 010-3266-0234","staff":"김대한","memoId":"m_57082710"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S039489","name":"지에이코리아주식회사(전북행복드림사업부)","address":"전남 순천시 백연길86,","phone":"전화 061-722-6671","staff":"김대한","memoId":"m_65A1DEC1"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S010466","name":"에이아이지어드바이저 주식회사(광주)","address":"전남 순천시 봉화3길14-12,","phone":"전화 061-721-0950","staff":"김대한","memoId":"m_3BCDAF95"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S045621","name":"주식회사 지금융코리아(도안)","address":"전남 순천시 비봉2길3-18,","phone":"전화 061-725-8606","staff":"김대한","memoId":"m_2BCB349D"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S001564","name":"주식회사 아너스금융서비스(순천)","address":"전남 순천시 시민로 24 (장천동)","phone":"전화 061-727-4300","staff":"김대한","memoId":"m_FAC9252"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S040086","name":"(주)글로벌금융판매(오에스케이행복키움순천)","address":"전남 순천시 연동남1길34,","phone":"전화 061-725-3312","staff":"김대한","memoId":"m_3CAFA1CD"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S010524","name":"더케이에셋보험대리점(주) 본사","address":"전남 순천시 연향번영길 102 (연향동)","phone":"전화 061-725-1041","staff":"김대한","memoId":"m_46F1E416"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S019890","name":"케이지에이에셋(주)(순천)","address":"전남 순천시 연향번영길102,","phone":"전화 061-725-7802","staff":"김대한","memoId":"m_6FFB14E0"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S023153","name":"지에이코리아주식회사(가온순천)","address":"전남 순천시 연향번영길129,","phone":"전화 061-726-1649","staff":"김대한","memoId":"m_46491BF8"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S029406","name":"인카금융서비스(주)(이룸)","address":"전남 순천시 왕궁1길29,","phone":"전화 061-742-7179","staff":"김대한","memoId":"m_7C06585C"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S026024","name":"신한금융플러스 주식회사(더믿음)","address":"전남 순천시 왕궁중앙길2,","phone":"전화 010-2918-7301","staff":"김대한","memoId":"m_3F8C4A56"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S018394","name":"케이지에이에셋(주)(엔에스)","address":"전남 순천시 왕지1길19,","phone":"전화 061-811-2244","staff":"김대한","memoId":"m_7163E1EC"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S038840","name":"아이에프에이(주)(에인스메이저순천지점)","address":"전남 순천시 왕지1길3-26,","phone":"전화 010-8475-3200","staff":"김대한","memoId":"m_2E07DB15"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S042595","name":"지에이코리아주식회사(투게더지사)","address":"전남 순천시 왕지1길9,","phone":"전화 061-724-0120","staff":"김대한","memoId":"m_429DA330"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S000839","name":"(주)에이플러스에셋어드바이저(탑앤탑)","address":"전남 순천시 왕지2길15,","phone":"전화 061-727-2686","staff":"김대한","memoId":"m_5A88FDE1"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S018559","name":"아이에프에이(주)(에인스한빛리더스순천지점)","address":"전남 순천시 왕지3길18-28,","phone":"전화 061-901-6400","staff":"김대한","memoId":"m_1E70B7D7"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S017400","name":"인카금융서비스(주)(순천성공)","address":"전남 순천시 왕지3길18-72,","phone":"전화 061-723-3457","staff":"김대한","memoId":"m_445B820C"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S027604","name":"지에이코리아주식회사(동천)","address":"전남 순천시 왕지4길10,","phone":"전화 061-721-3713","staff":"김대한","memoId":"m_358ECFC7"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S008250","name":"케이지에이에셋(주)(천야지사그랜드)","address":"전남 순천시 왕지4길4-9,","phone":"전화 061-727-9711","staff":"김대한","memoId":"m_53153977"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S031719","name":"케이지에이에셋(주)(하나로지사순천)","address":"전남 순천시 왕지4길4-9,","phone":"전화 061-722-1562","staff":"김대한","memoId":"m_64392AEA"},
  {"quarter":"GA_조직","bank":"메리츠","center":"순천","branchNo":"D003164","name":"호남GA본부","address":"전남 순천시 왕지4길7,","phone":"전화 062-350-5453","staff":"김대한","memoId":"m_6479A58"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S001012","name":"유퍼스트보험마케팅(주)(순천지사)","address":"전남 순천시 왕지4길7,","phone":"전화 061-742-3557","staff":"김대한","memoId":"m_38C3A8C0"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S003504","name":"지에이코리아주식회사(플러스순천)","address":"전남 순천시 왕지5길34,","phone":"전화 061-721-1997","staff":"김대한","memoId":"m_4D8FC41B"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S018346","name":"지에이코리아주식회사(브이아이피성공)","address":"전남 순천시 왕지5길6,","phone":"전화 010-2611-0776","staff":"김대한","memoId":"m_1D32A445"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S042734","name":"지에이코리아주식회사(엑스포신세계)","address":"전남 순천시 왕지5길6,","phone":"전화 061-727-4601","staff":"김대한","memoId":"m_52212823"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S017590","name":"유퍼스트보험마케팅(주)(새순천)","address":"전남 순천시 왕지로6,","phone":"전화 061-723-1139","staff":"김대한","memoId":"m_698B0B81"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S018467","name":"(주)유엔아이인슈컨설팅(왕운지점)","address":"전남 순천시 왕지로8,","phone":"전화 061-811-2517","staff":"김대한","memoId":"m_8C241DC"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S020224","name":"케이지에이에셋(주)(정원)","address":"전남 순천시 율산3길112,","phone":"전화 010-3623-6368","staff":"김대한","memoId":"m_7013BDCD"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S026647","name":"한화생명금융서비스(주)(전남)","address":"전남 순천시 이수로13,","phone":"전화 061-743-8090","staff":"김대한","memoId":"m_2AE9EF32"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D003659","name":"순천탑2본부(1지점)","address":"전남 순천시 이수로296,","phone":"전화 061-729-5742","staff":"김대한","memoId":"m_7B721AE7"},
  {"quarter":"PA_본부","bank":"메리츠","center":"순천","branchNo":"D001141","name":"파트너스호남센터","address":"전남 순천시 이수로314,","phone":"전화 061-729-5902","staff":"김대한","memoId":"m_7AECD366"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D003303","name":"순천더조은본부","address":"전남 순천시 이수로314,","phone":"전화 061-759-5401","staff":"김대한","memoId":"m_21903CD2"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D003304","name":"순천위너스본부","address":"전남 순천시 이수로314,","phone":"전화 061-759-5301","staff":"김대한","memoId":"m_78E94E80"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D003305","name":"탑본부","address":"전남 순천시 이수로314,","phone":"전화 061-729-5742","staff":"김대한","memoId":"m_4765C03D"},
  {"quarter":"보상/손사","bank":"메리츠","center":"순천","branchNo":"D007245","name":"호남대물보상센터","address":"전남 순천시 이수로314,","phone":"전화 010-5151-3427","staff":"김대한","memoId":"m_541302A6"},
  {"quarter":"TA_조직","bank":"메리츠","center":"순천","branchNo":"D007260","name":"순천센터","address":"전남 순천시 이수로314,","phone":"전화 010-6584-1153","staff":"김대한","memoId":"m_2C510E6A"},
  {"quarter":"TA_교육장","bank":"메리츠","center":"순천","branchNo":"D007558","name":"순천센터","address":"전남 순천시 이수로314,","phone":"전화 010-6584-1153","staff":"김대한","memoId":"m_2C510E6A"},
  {"quarter":"TA_교육장","bank":"메리츠","center":"순천","branchNo":"D007788","name":"순천센터","address":"전남 순천시 이수로314,","phone":"전화 010-6584-1153","staff":"김대한","memoId":"m_2C510E6A"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D008300","name":"순천베스트본부","address":"전남 순천시 이수로314,","phone":"전화 061-759-5401","staff":"김대한","memoId":"m_46CF134B"},
  {"quarter":"TA_교육장","bank":"메리츠","center":"순천","branchNo":"D009719","name":"순천센터","address":"전남 순천시 이수로314,","phone":"전화 061-729-5686","staff":"김대한","memoId":"m_2C510E6A"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S036370","name":"에이비에이금융서비스 유한회사(순천)","address":"전남 순천시 장선배기1길9-8,","phone":"전화 061-921-9510","staff":"김대한","memoId":"m_7A9500BE"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S003500","name":"지에이코리아주식회사(금당)","address":"전남 순천시 장선배기길 27","phone":"전화 061-727-3026","staff":"김대한","memoId":"m_3572C3B3"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S042760","name":"주식회사 지금융코리아(더존에셋순천칠)","address":"전남 순천시 장자보1길61,","phone":"전화 061-726-3996","staff":"김대한","memoId":"m_70672CA5"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S043378","name":"인카금융서비스(주)(바른비즈)","address":"전남 순천시 조례신대앞길20,","phone":"전화 010-9450-2606","staff":"김대한","memoId":"m_4CB00425"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D010781","name":"호남제일본부","address":"전남 순천시 충효로 142,","phone":"전화 061-727-6577","staff":"김대한","memoId":"m_772B5008"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S015020","name":"주식회사 지금융코리아(위드)","address":"전남 순천시 충효로109,","phone":"전화 061-725-2315","staff":"김대한","memoId":"m_2C1AF9F1"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S021606","name":"케이지에이에셋(주)(천야지사뉴명인)","address":"전남 순천시 충효로117,","phone":"전화 061-742-5544","staff":"김대한","memoId":"m_559983B8"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S025652","name":"케이지에이에셋(주)(천야지사글로벌)","address":"전남 순천시 충효로117,","phone":"전화 061-742-7600","staff":"김대한","memoId":"m_531DCAEF"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D006901","name":"호남제일2본부","address":"전남 순천시 충효로142,","phone":"전화 010-9953-1530","staff":"김대한","memoId":"m_5972F6D8"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D007814","name":"호남제일2본부","address":"전남 순천시 충효로142,","phone":"전화 061-727-6577","staff":"김대한","memoId":"m_5972F6D8"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D010155","name":"호남제일혁신본부","address":"전남 순천시 충효로142,","phone":"전화 061-727-6577","staff":"김대한","memoId":"m_7D29D53E"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D010782","name":"호남제일혁신본부","address":"전남 순천시 충효로142,","phone":"전화 010-6636-7300","staff":"김대한","memoId":"m_7D29D53E"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S020105","name":"신한금융플러스 주식회사(순천드림)","address":"전남 순천시 충효로15,","phone":"전화 061-722-2225","staff":"김대한","memoId":"m_45756D19"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S015199","name":"(주)드림라이프(브라보)","address":"전남 순천시 태봉길41,","phone":"전화 061-724-0012","staff":"김대한","memoId":"m_464B01FB"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S003214","name":"지에이코리아주식회사(케이에스)","address":"전남 순천시 팔마3길 12 (연향동)","phone":"전화 061-742-8938","staff":"김대한","memoId":"m_40674485"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S024899","name":"지에이코리아주식회사(홍인)","address":"전남 순천시 팔마3길14-6,","phone":"전화 061-727-0087","staff":"김대한","memoId":"m_3620B597"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S042625","name":"주식회사 지금융코리아(두드림)","address":"전남 순천시 팔마4길8,","phone":"전화 061-725-2315","staff":"김대한","memoId":"m_25509E04"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S046013","name":"지에이코리아주식회사(든든라이프)","address":"전남 순천시 팔마5길61,","phone":"전화 010-5623-3265","staff":"김대한","memoId":"m_4AFB565"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S016288","name":"프라임에셋(주)(순천3지점)","address":"전남 순천시 하대석길58,","phone":"전화 061-752-2004","staff":"김대한","memoId":"m_110B9766"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S015236","name":"지에이코리아주식회사(순천)","address":"전남 순천시 하대석길69,","phone":"전화 061-742-2590","staff":"김대한","memoId":"m_35CB7ACA"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S003350","name":"지에이코리아주식회사(플러스팔마)","address":"전남 순천시 하풍동길 26 (풍덕동)","phone":"전화 061-743-3800","staff":"김대한","memoId":"m_4DD585BF"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S024104","name":"케이지에이에셋(주)(신대)","address":"전남 순천시 해룡면 매안4길32,","phone":"전화 061-727-3822","staff":"김대한","memoId":"m_6FFB0988"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S040459","name":"주식회사 지금융코리아(슬기로운금융)","address":"전남 순천시 해룡면 매안로133,","phone":"전화 061-721-3961","staff":"김대한","memoId":"m_5A071D75"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S043846","name":"(주)스카이블루에셋(순천사업본부)","address":"전남 순천시 해룡면 매안로137,","phone":"전화 061-901-0170","staff":"김대한","memoId":"m_4CB2A32A"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S015348","name":"프라임에셋(주)(순천6지점)","address":"전남 순천시 해룡면 순광로234-9,","phone":"전화 061-721-3580","staff":"김대한","memoId":"m_110D3C89"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S043780","name":"지에이코리아주식회사(플러스원앙글로리)","address":"전남 순천시 해룡면 신대로4,","phone":"전화 061-653-1000","staff":"김대한","memoId":"m_5A4F2CF9"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S038427","name":"(주)메타리치(호남스타)","address":"전남 순천시 해룡면 신대로45,","phone":"전화 061-722-9330","staff":"김대한","memoId":"m_3225F291"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S029419","name":"인카금융서비스(주)(순천금당)","address":"전남 순천시 해룡면 조례못등길140,","phone":"전화 061-721-3010","staff":"김대한","memoId":"m_440AC727"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S040163","name":"피플라이프(주)(다옴)","address":"전남 순천시 해룡면 향매1길15-10,","phone":"전화 061-811-2523","staff":"김대한","memoId":"m_754BDAB1"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S043216","name":"인카금융서비스(주)(순천아이케이신대지점)","address":"전남 순천시 해룡면 향매1길15-10,","phone":"전화 061-721-5505","staff":"김대한","memoId":"m_1FDB983D"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S045332","name":"메가(주)(인슈하나로)","address":"전남 순천시 해룡면 향매로105,","phone":"전화 061-726-8873","staff":"김대한","memoId":"m_13D57B29"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S042234","name":"인카금융서비스(주)(디바인지점)","address":"전남 순천시 해룡면 향매로126,","phone":"전화 061-811-2016","staff":"김대한","memoId":"m_42F2B230"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S040662","name":"(주)현대홈쇼핑(순천지점)","address":"전남 순천시 해룡면 향매로135,","phone":"전화 061-811-2577","staff":"김대한","memoId":"m_6655CF63"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S018623","name":"(주)유엔아이인슈컨설팅(브라보)","address":"전남 여수시 거북선공원1길6,","phone":"전화 061-810-6601","staff":"김대한","memoId":"m_169C8118"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S024347","name":"아이에프에이(주)(브이아이피)","address":"전남 여수시 도원로263,","phone":"전화 061-684-8440","staff":"김대한","memoId":"m_AB38F3C"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S015036","name":"(주)드림라이프(여천)","address":"전남 여수시 도원로279,","phone":"전화 061-686-1335","staff":"김대한","memoId":"m_40544DB7"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S003362","name":"지에이코리아주식회사(순천)","address":"전남 여수시 망마로21,","phone":"전화 061-651-7678","staff":"김대한","memoId":"m_35CB7ACA"},
  {"quarter":"TA_대리점","bank":"메리츠","center":"순천","branchNo":"S019874","name":"마산본부(3지점)","address":"전남 여수시 망마로21,","phone":"전화 010-3633-5225","staff":"김대한","memoId":"m_285AE2D6"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S022522","name":"(주)엠금융서비스(메이저)","address":"전남 여수시 망마로21,","phone":"전화 061-681-2788","staff":"김대한","memoId":"m_70A74714"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S038973","name":"에이비에이금융서비스 유한회사(프로)","address":"전남 여수시 망마로21,","phone":"전화 061-921-9510","staff":"김대한","memoId":"m_7AE2D166"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S044416","name":"아이에프에이(주)(에인스메이저여수지점)","address":"전남 여수시 망마로21,","phone":"전화 061-681-2788","staff":"김대한","memoId":"m_6D411AE1"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S023553","name":"굿리치주식회사(빛고을본부지점)","address":"전남 여수시 망마로31,","phone":"전화 010-8513-1467","staff":"김대한","memoId":"m_754ACB77"},
  {"quarter":"GA_조직","bank":"메리츠","center":"순천","branchNo":"D010769","name":"호남GA본부","address":"전남 여수시 무선로147,","phone":"전화 010-9213-8997","staff":"김대한","memoId":"m_6479A58"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S041526","name":"인카금융서비스(주)(제이어스사업단여수지점)","address":"전남 여수시 무선로239-18,","phone":"전화 061-682-0233","staff":"김대한","memoId":"m_63DA7B7F"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S001005","name":"유퍼스트보험마케팅(주)(여수지사)","address":"전남 여수시 문수로 15-1","phone":"전화 061-651-1257","staff":"김대한","memoId":"m_77FCE88C"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S003172","name":"지에이코리아주식회사(여수)","address":"전남 여수시 문수로 80 (문수동)","phone":"전화 061-653-6868","staff":"김대한","memoId":"m_35DA5796"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S012004","name":"(주)유엔아이인슈컨설팅(글로리)","address":"전남 여수시 문수로15-1,","phone":"전화 010-3708-3051","staff":"김대한","memoId":"m_DD32924"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S015820","name":"케이지에이에셋(주)(스타에프지에이)","address":"전남 여수시 문수로33,","phone":"전화 061-651-1026","staff":"김대한","memoId":"m_263403A0"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S003352","name":"지에이코리아주식회사(플러스여수)","address":"전남 여수시 문수로35-1,","phone":"전화 061-655-0138","staff":"김대한","memoId":"m_4D9EA0E7"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S025901","name":"지에이코리아주식회사(플러스여수)","address":"전남 여수시 문수로35-1,","phone":"전화 061-655-0138","staff":"김대한","memoId":"m_4D9EA0E7"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S032487","name":"지에이코리아주식회사(플러스원앙)","address":"전남 여수시 문수로76,","phone":"전화 061-653-1000","staff":"김대한","memoId":"m_4DA2D62C"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S044857","name":"지에이코리아주식회사(플러스원앙)","address":"전남 여수시 문수로76,","phone":"전화 061-653-1000","staff":"김대한","memoId":"m_4DA2D62C"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S039583","name":"메가(주)(인슈여수)","address":"전남 여수시 선소로105,","phone":"전화 061-691-8977","staff":"김대한","memoId":"m_424A47F0"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S020673","name":"지에이코리아주식회사(예향학동)","address":"전남 여수시 선소로63,","phone":"전화 061-691-1080","staff":"김대한","memoId":"m_2623D9BB"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S018482","name":"신한금융플러스 주식회사(여천)","address":"전남 여수시 선원4길7-5,","phone":"전화 061-922-0001","staff":"김대한","memoId":"m_442DEC4E"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S024677","name":"주식회사 지금융코리아(에스앤피학동)","address":"전남 여수시 소라면 죽림로5,","phone":"전화 061-807-3005","staff":"김대한","memoId":"m_461CDE17"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S042376","name":"인카금융서비스(주)(제이어스명인리더스원지점)","address":"전남 여수시 소호5길6,","phone":"전화 061-682-1257","staff":"김대한","memoId":"m_1F5D6545"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S044692","name":"인카금융서비스(주)(다이렉트오케이여수)","address":"전남 여수시 시청동1길17,","phone":"전화 061-523-1234","staff":"김대한","memoId":"m_6083A13E"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S014533","name":"(주)에이플러스에셋어드바이저(여수)","address":"전남 여수시 시청로42,","phone":"전화 061-685-5119","staff":"김대한","memoId":"m_311A6293"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S027710","name":"지에이코리아주식회사(다모아)","address":"전남 여수시 시청로84,","phone":"전화 061-691-3350","staff":"김대한","memoId":"m_66AF798F"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S018147","name":"지에이코리아주식회사(브이아이피)","address":"전남 여수시 시청로9,","phone":"전화 061-682-7979","staff":"김대한","memoId":"m_417E36D2"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S043007","name":"주식회사 지금융코리아(에스앤피그린)","address":"전남 여수시 시청서2길8,","phone":"전화 061-691-2364","staff":"김대한","memoId":"m_45761B2D"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D008275","name":"수원본부","address":"전남 여수시 신기남2길20,","phone":"전화 031-8002-1502","staff":"김대한","memoId":"m_2C3593A6"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S040711","name":"인카금융서비스(주)(원탑사업단)","address":"전남 여수시 신기남3길10,","phone":"전화 010-4495-0017","staff":"김대한","memoId":"m_14A798D0"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S017515","name":"케이지에이에셋(주)(동광주)","address":"전남 여수시 신기북4길11-1,","phone":"전화 061-684-7875","staff":"김대한","memoId":"m_671F5AAA"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D000868","name":"탑본부(여수지점)","address":"전남 여수시 신월로96,","phone":"전화 061-652-1566","staff":"김대한","memoId":"m_78011D02"},
  {"quarter":"TA_교육장","bank":"메리츠","center":"순천","branchNo":"D000869","name":"순천센터","address":"전남 여수시 신월로96,","phone":"전화 061-650-1501","staff":"김대한","memoId":"m_2C510E6A"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D003302","name":"탑본부","address":"전남 여수시 신월로96,","phone":"전화 061-650-1502","staff":"김대한","memoId":"m_4765C03D"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D007412","name":"탑2본부","address":"전남 여수시 신월로96,","phone":"전화 061-650-1505","staff":"김대한","memoId":"m_30FB6DA1"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D007413","name":"탑본부","address":"전남 여수시 신월로96,","phone":"전화 061-650-1505","staff":"김대한","memoId":"m_4765C03D"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D008010","name":"탑3본부(여수지점)","address":"전남 여수시 신월로96,","phone":"전화 061-650-1502","staff":"김대한","memoId":"m_1125C59D"},
  {"quarter":"TA_본부","bank":"메리츠","center":"순천","branchNo":"D008323","name":"탑본부","address":"전남 여수시 신월로96,","phone":"전화 061-650-1502","staff":"김대한","memoId":"m_4765C03D"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S006525","name":"(주)보험세계","address":"전남 여수시 쌍봉로253,","phone":"전화 061-685-7715","staff":"김대한","memoId":"m_76532CE4"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S040340","name":"인카금융서비스(주)(케이디여수)","address":"전남 여수시 쌍봉로99,","phone":"전화 010-8666-6280","staff":"김대한","memoId":"m_7E1BE5C6"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S003351","name":"지에이코리아주식회사(플러스여수)","address":"전남 여수시 여문문화1길78,","phone":"전화 061-661-0138","staff":"김대한","memoId":"m_4D9EA0E7"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S025902","name":"지에이코리아주식회사(플러스여수)","address":"전남 여수시 여문문화1길78,","phone":"전화 061-655-0138","staff":"김대한","memoId":"m_4D9EA0E7"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S015381","name":"케이지에이에셋(주)(하나로지사벧엘)","address":"전남 여수시 여문문화길57-1,","phone":"전화 061-655-1020","staff":"김대한","memoId":"m_642114F1"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S018291","name":"(주)유엔아이인슈컨설팅(스타지점)","address":"전남 여수시 여서1로21,","phone":"전화 061-810-0115","staff":"김대한","memoId":"m_4B782C36"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S003482","name":"지에이코리아주식회사(엑스포)","address":"전남 여수시 예울마루로 35-38 (웅천동)","phone":"전화 061-685-4602","staff":"김대한","memoId":"m_71341C00"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S016818","name":"(주)드림라이프(브라보여수)","address":"전남 여수시 예울마루로43,","phone":"전화 061-642-0025","staff":"김대한","memoId":"m_875B6D5"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S022602","name":"아이에프에이(주)(에인스한빛리더스여수지점)","address":"전남 여수시 웅남1길25,","phone":"전화 061-686-7626","staff":"김대한","memoId":"m_5DA9F7A3"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S020152","name":"프라임에셋(주)(여수14지점)","address":"전남 여수시 웅천2길5-60,","phone":"전화 010-6474-7403","staff":"김대한","memoId":"m_367EBCA1"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S038070","name":"인카금융서비스(주)(순천아이케이신대지점)","address":"전남 여수시 웅천3길8-14,","phone":"전화 061-685-3547","staff":"김대한","memoId":"m_1FDB983D"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S028541","name":"(주)에프엠에셋(인포벨금융서비스_뉴호남)","address":"전남 여수시 웅천남5로42,","phone":"전화 010-5007-5950","staff":"김대한","memoId":"m_5B1F55D3"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S045759","name":"(주)메타리치(여수본부)","address":"전남 여수시 웅천남6로11,","phone":"전화 010-6590-0133","staff":"김대한","memoId":"m_14B3DBC7"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S039616","name":"(주)스카이블루에셋(여수사업본부)","address":"전남 여수시 웅천남6로35,","phone":"전화 061-920-0037","staff":"김대한","memoId":"m_3F3B0810"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S021511","name":"메가(주)(인슈전남본부)","address":"전남 여수시 웅천남6로41,","phone":"전화 061-807-2015","staff":"김대한","memoId":"m_1D8B1304"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S040801","name":"주식회사 더탑아이앤아이(여수지점)","address":"전남 여수시 웅천로19-9,","phone":"전화 061-810-5788","staff":"김대한","memoId":"m_446FBFD4"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S040539","name":"굿리치주식회사(백억사업단지점)","address":"전남 여수시 웅천로90,","phone":"전화 061-920-4750","staff":"김대한","memoId":"m_68A9431E"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S024694","name":"주식회사 지금융코리아(에스앤피여수)","address":"전남 여수시 웅천북로38,","phone":"전화 061-686-6890","staff":"김대한","memoId":"m_45DD1589"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S026591","name":"인카금융서비스(주)(다이렉트여수지점)","address":"전남 여수시 장성1길9-1,","phone":"전화 061-692-6353","staff":"김대한","memoId":"m_5CC6177C"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S045631","name":"주식회사 지금융코리아(에스앤피파인에셋)","address":"전남 여수시 주삼덕양로189,","phone":"전화 061-684-8283","staff":"김대한","memoId":"m_254E7AD8"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S017588","name":"(주)글로벌금융판매(퍼스트여수)","address":"전남 여수시 학동북2길14-5,","phone":"전화 061-682-0090","staff":"김대한","memoId":"m_273D851"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S039668","name":"지에이코리아주식회사(동천여수)","address":"전남 여수시 학동북2길14-5,","phone":"전화 061-692-3713","staff":"김대한","memoId":"m_57E42712"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S039618","name":"지에이코리아주식회사(엑스포감탄)","address":"전남 여수시 학동북4길12,","phone":"전화 010-3646-1895","staff":"김대한","memoId":"m_11A14AD7"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S045447","name":"주식회사 더금융서비스(더금융서비스 더해드림 케이엔엠지점)","address":"전남 여수시 화산로126,","phone":"전화 061-692-5007","staff":"김대한","memoId":"m_30EA6940"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S036158","name":"엑셀금융서비스(주)(해남사업단)","address":"전남 여수시 화산로37,","phone":"전화 010-3623-6523","staff":"김대한","memoId":"m_2AF3767"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S040994","name":"케이지에이에셋(주)(여수플러스)","address":"전남 여수시 흥국상가길13,","phone":"전화 061-375-6138","staff":"김대한","memoId":"m_5BD36548"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S043721","name":"주식회사 지금융코리아(인스비즈장흥)","address":"전남 장흥군 장흥읍 동교1길17-10,","phone":"전화 010-8990-3905","staff":"김대한","memoId":"m_3D0252C1"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S019958","name":"케이지에이에셋(주)(하누리)","address":"전남 장흥군 장흥읍 동교1길40,","phone":"전화 010-9601-7545","staff":"김대한","memoId":"m_7990942C"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S021281","name":"(주)엠금융서비스(장흥)","address":"전남 장흥군 장흥읍 동교1길47,","phone":"전화 061-864-4800","staff":"김대한","memoId":"m_58F92C00"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S016948","name":"(주)글로벌금융판매(케이엘인슈장흥)","address":"전남 장흥군 장흥읍 동교3길5,","phone":"전화 010-9887-3051","staff":"김대한","memoId":"m_3152DEA"},
  {"quarter":"GA_대리점","bank":"메리츠","center":"순천","branchNo":"S031089","name":"주식회사 삼성금융파트너스(장흥보성)","address":"전남 장흥군 장흥읍 흥성로3,","phone":"전화 061-862-4831","staff":"김대한","memoId":"m_4DB08C54"},
  {"quarter":"4","bank":"신한은행","center":"순천","branchNo":"","name":"순천법원","address":"전남광주 순천시 왕지로 21","phone":"","staff":"장창형","memoId":"m_383A14E1"},
  {"quarter":"4","bank":"신한은행","center":"순천","branchNo":"","name":"여수금융센터","address":"전남광주 여수시 시청로 6","phone":"","staff":"김준호","memoId":"m_4D94D47F"},
  {"quarter":"4","bank":"전북은행","center":"순천","branchNo":"","name":"남원","address":"전북특별자치도 남원시 시청로 50","phone":"","staff":"김대한","memoId":"m_4DCDA3A7"}
];
